# Generated by Django 6.0.4 on 2026-05-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('production', 'Production')], max_length=50),
        ),
    ]
